apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
      volumes:
      - name: html
        configMap:
          name: nginx-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Site de démonstration Alcyor</title>
        <meta http-equiv="refresh" content="3">
    </head>
    <body>
        <h1>démonstration Alcyor avec le log d'avant</h1>
        <img height="100" src="https://scontent-cdg2-1.xx.fbcdn.net/v/t1.18169-9/11899899_1187204854638612_3186127321407323695_n.png?_nc_cat=108&ccb=1-7&_nc_sid=cdbe9c&_nc_ohc=HkkdozzCJEkAX-4xUAe&_nc_ht=scontent-cdg2-1.xx&oh=00_AfAdP8v4ByJ1l9TYx_gyekk_SGQ3iCxck-sRng3nvXs1tg&oe=642054FE">
        <script>
            setTimeout(function() {
                document.body.innerHTML += "<p>refresh automatique applicatif</p>";
           }, 2000);
        </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    nodePort: 32111
    port: 80
    targetPort: 80
  type: NodePort
